### ISSUE TITLE
The controller for path &#39;/compression/contracts&#39; was not found or does not implement IController.

### ISSUE THREAD

**Issue by Adecus** [NTaylorMullen/SignalR.Compression#7]
When I build the projects, add the lines specified in the readme I get the following error:
The controller for path &#39;/compression/contracts&#39; was not found or does not implement IController.
   at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)
   at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName)
   at Instrumar.ProductionDashboard.Service.CustomControllerFactory.CreateController(RequestContext aRequestContext, String aControllerName) in c:\Repositories\Fiber\Dashboard\Instrumar.ProductionDashboard\Service\CustomControllerFactory.cs:line 50
   at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory)
   at System.Web.Mvc.MvcHandler.<>c__DisplayClass6.<BeginProcessRequest>b__2()
   at System.Web.Mvc.SecurityUtil.<>c__DisplayClassb`1.<ProcessInApplicationTrust>b__a()
   at System.Web.Mvc.SecurityUtil.<GetCallInAppTrustThunk>b__0(Action f)
   at System.Web.Mvc.SecurityUtil.ProcessInApplicationTrust(Action action)
   at System.Web.Mvc.SecurityUtil.ProcessInApplicationTrust[TResult](Func`1 func)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

---

I did everything in the readme besides adding [Payload] to objects being sent over signalR. Mainly because we're sending List<Dictionary<string, object>>. I could create a new type that exposed the list of dictionaries and put [Payload] at the top if that's what is needed but I don't think that is related to the problem above. 

Also i'll note that i'm building against .NET 4.0 and SignalR 1.2.1. I also didn't think this would be related to the above problem.

Is this project still active? I noticed there hasn't been anything done to this since March 23, 2013 and there have been no releases. I could manually implement IHttpClient for gzip compression as outlined here http://stackoverflow.com/questions/12717101/signalr-wth-gzip-compression but would prefer to use an official solution.

**Comment by NTaylorMullen** [comment]
Hah, hey man, sorry about your troubles. This actually isn't a supported project, just something I did in my free time to see how far I could push little bits of compression. Honestly I don't believe I ever finished it entirely so I'd recommend going with another approach :smile:

**Comment by Adecus** [comment]
No worries, I didn't spend a lot of time on building and getting it integrated. Would you recommend any compression techniques that would work well with SignalR in general or any best practices you may have picked up from your experience with this? If not no prob, and thanks for the update on the status of this!

**Comment by NTaylorMullen** [comment]
Ahh, no best practices from my experience sorry. Good luck!
